### ISSUE TITLE
package.json test command needs backslashes on windows

### ISSUE THREAD

**Issue by jespirit** [mozilla/vtt.js#127]
I'm working on a windows machine with git bash prompt. I need to change the forward slashes for the test command in `package.json` to run npm test, otherwise I get this. Is there another workaround?

```
> vtt@0.2.0 test c:\Users\Jeffrey\documents\projects\opensource\vtt.js
> ./node_modules/.bin/grunt && ./node_modules/.bin/mocha --recursive --reporter spec --timeout 60000
 --slow 40000 tests

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! weird error 1
npm ERR! not ok code 0
```

The test command needs to be:

```
"test": ".\\node_modules\\.bin\\grunt && .\\node_modules\\.bin\\mocha --recursive --reporter spec --timeout 60000 --slow 40000 tests"
```

**Comment by nimayneb** [comment]
You can use a cross-solution.

Try using/ to fix it with this kind of... ehm, hack?:
```json
...
"test": ".\"/node_modules/.bin/grunt\"   ...   "
...
```
All starting points in a relative path string are not part of a string scope (at this point):
..\"/path/path2/command"
."/path/path2/command"

You have to surround your path/commands here.

All following arguments (with points and forward slashes) for a command are now part of a string scope:
..\"/path/path2/command" "../argument/path/path2"

I'm not really happy to have found this solution, but... hey, a way that really works both on Linux and Windows. Maybe macOS. I don't check this yet.

**Comment by gijswijs** [comment]
I can confirm that 

```
.\"
```

in front of the path works!
