### ISSUE TITLE
Build dist & update npm to include latest fixes

### ISSUE THREAD

**Issue by johnBartos** [mozilla/vtt.js#356]
There's been 4 PRs merged since the last dist build, including a fix for a breaking change (https://github.com/mozilla/vtt.js/pull/355). The npm package needs to be updated.

@rillian 

If you guys are looking for a maintainer I'd be happy to pitch in. We use vtt.js in jwplayer so I'm pretty familiar with it.

**Comment by rillian** [comment]
Maintainer help would be great. I'm the primary reviewer for changes to the version in gecko, but I haven't had much time to work on the stand-alone version. And I don't know much about node. How do I publish a new package?

**Comment by rillian** [comment]
@RickEyre Could you please add me to the npm package for vtt.js?

**Comment by gkatsev** [comment]
I'd be happy to help as well, if necessary. We use vttjs in videojs and am also familiar.

It seems that this project is set up to do a release via the grunt task. `grunt release`. I believe after running that you can run `npm publish`.

**Comment by rillian** [comment]
Ok thanks. Should this be v0.13.0 or v0.12.2?

**Comment by gkatsev** [comment]
probably 0.13.0

**Comment by rillian** [comment]
Pinging @RickEyre on the npmjs.com permissions.
