### ISSUE TITLE
Update the NPM version (which is still the 0.12.1 version)

### ISSUE THREAD

**Issue by lbebber** [mozilla/vtt.js#360]

**Comment by rillian** [comment]
Yesterday I pushed a package of the v0.13.0 tag to npm. Many [pages](https://npmjs.com/package/vtt.js) still say '0.12.1 is the latest' but the version badge shows 0.13 and that what I get from `npm install`. 

@gkatsev, @johnBartos Any idea what I need to do to fix the npm package page?

**Comment by rillian** [comment]
Apparently this is a known bug with the site. Starring and then unstarring the package triggered an update. We should be good.

**Comment by gkatsev** [comment]
As long as `npm dist-tag ls vtt.js` says that the `latest` is the version you want, that's all that matters, really :)
