### ISSUE TITLE
[Usage Question] Number representation different locales

### ISSUE THREAD

**Issue by goatandsheep** [mozilla/vtt.js#375]
Does WebVTT work differently under different locales? I mean numbers in japanese and german locales are represented differently. I wanted to confirm if WebVTT files are formed different too

**Comment by silviapfeiffer** [comment]
WebVTT provides all the information for rendering captions in didn't languages and locales. You just need to without enough files for all the different languages. The choice which WebVTT file to render is up to the player (or browser).

**Comment by gkatsev** [comment]
Yes, WebVTT requires the timestamp to be in the `00:00:00.000` format and that piece is not localized.
I believe the srt format that webvtt was originally based on required commas.

**Comment by silviapfeiffer** [comment]
@goatandsheep that's the internal format of WebVTT - it's like an encoding. What you do in a video player is up to the video player - they will convert it to being usable.

**Comment by goatandsheep** [comment]
Thank you for clarifying!
